//! Integration + unit tests for **CON-001: outbound connection via `connect_peer` semantics**.
//!
//! ## Traceability
//!
//! - **Spec + matrix:** [`CON-001.md`](../docs/requirements/domains/connection/specs/CON-001.md)
//! - **Normative:** [`NORMATIVE.md`](../docs/requirements/domains/connection/NORMATIVE.md)
//! - **SPEC:** [`SPEC.md`](../docs/resources/SPEC.md) §5.1
//!
//! ## Proof strategy
//!
//! **TLS / connector rows** exercise [`dig_gossip::load_ssl_cert`] and [`dig_gossip::create_native_tls_connector`]
//! (rustls equivalent when `--features rustls` only — STR-004). **Integration rows** spin up the local
//! [`common::wss_full_node`] acceptor so [`dig_gossip::GossipHandle::connect_to`] runs the full
//! `wss://` + [`Handshake`](dig_gossip::Handshake) + [`RequestPeers`](dig_gossip::RequestPeers) sequence
//! against a [`NodeType::FullNode`](dig_gossip::NodeType) responder, then assert [`AddressManager`] ingestion
//! via the [`GossipHandle::__con001_last_address_batch_for_tests`] hook.

mod common;

use std::time::{SystemTime, UNIX_EPOCH};

use dig_gossip::GossipHandle;
use dig_gossip::{
    create_native_tls_connector, load_ssl_cert, ChiaCertificate, GossipError, GossipService,
    Handshake, NodeType, PeerId, TimestampedPeerInfo,
};

/// **Row:** `test_tls_cert_load` — PEM generated by STR-005 helpers loads via upstream `load_ssl_cert`.
#[test]
fn test_tls_cert_load() {
    let dir = common::test_temp_dir();
    let (c, k) = common::generate_test_certs(dir.path());
    let loaded = load_ssl_cert(&c, &k).expect("load_ssl_cert");
    assert!(!loaded.cert_pem.is_empty());
    assert!(!loaded.key_pem.is_empty());
}

/// **Row:** `test_tls_cert_generate` — fresh identity for first-run / harness scenarios.
#[test]
fn test_tls_cert_generate() {
    let cert = ChiaCertificate::generate().expect("ChiaCertificate::generate");
    assert!(!cert.cert_pem.is_empty());
}

/// **Row:** `test_connector_creation` — CON-001 requires a [`tokio_tungstenite::Connector`] from node material.
#[test]
fn test_connector_creation() {
    let dir = common::test_temp_dir();
    let (c, k) = common::generate_test_certs(dir.path());
    let tls = load_ssl_cert(&c, &k).expect("load");
    let _connector = create_native_tls_connector(&tls).expect("create_native_tls_connector");
}

/// **Row:** `test_peer_connection_wrapping` — field wiring matches [`Handshake`] / outbound semantics (API-005 layout).
///
/// **Note:** Uses STR-005 [`common::mock_peer_connection`] for a real [`dig_gossip::Peer`] handle without CON-002 listener.
#[tokio::test]
async fn test_peer_connection_wrapping() {
    let hs = Handshake {
        network_id: common::test_network_id().to_string(),
        protocol_version: "0.0.37".to_string(),
        software_version: "unit-test/1".to_string(),
        server_port: 8444,
        node_type: NodeType::FullNode,
        capabilities: vec![(1, "x".to_string())],
    };
    let mut base = common::mock_peer_connection(true).await;
    base.node_type = hs.node_type;
    base.protocol_version = hs.protocol_version.clone();
    base.software_version = hs.software_version.clone();
    base.peer_server_port = hs.server_port;
    base.capabilities = hs.capabilities.clone();
    assert!(base.is_outbound);
    let _: dig_gossip::Peer = base.peer;
    let _: tokio::sync::mpsc::Receiver<dig_gossip::Message> = base.inbound_rx;
}

/// **Row:** `test_creation_time_set` — [`PeerConnection::creation_time`] is Unix seconds near “now”.
#[tokio::test]
async fn test_creation_time_set() {
    let before = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let pc = common::mock_peer_connection(true).await;
    let after = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();
    assert!(
        pc.creation_time >= before.saturating_sub(1) && pc.creation_time <= after.saturating_add(1),
        "creation_time {} not near [{before},{after}]",
        pc.creation_time
    );
}

async fn running_client() -> (tempfile::TempDir, GossipService, GossipHandle) {
    let dir = common::test_temp_dir();
    let _ = common::generate_test_certs(dir.path());
    let cfg = common::test_gossip_config(dir.path());
    let svc = GossipService::new(cfg).expect("GossipService::new");
    let h = svc.start().await.expect("start");
    (dir, svc, h)
}

/// **Row:** `test_outbound_connect_handshake` — TLS client completes Chia handshake with matching `network_id`.
#[tokio::test]
async fn test_outbound_connect_handshake() {
    let (_cdir, _svc, h) = running_client().await;
    let server_dir = common::test_temp_dir();
    let (sc, sk) = common::generate_test_certs(server_dir.path());
    let server_cert = load_ssl_cert(&sc, &sk).expect("server tls");
    let net = common::test_network_id().to_string();
    let (addr, jh) =
        common::wss_full_node::spawn_one_shot_full_node(server_cert, net.clone(), vec![]).await;
    let pid = h.connect_to(addr).await.expect("outbound connect");
    assert_ne!(pid, PeerId::default());
    let batch = h.__con001_last_address_batch_for_tests();
    assert!(
        batch.is_some(),
        "add_to_new_table should run after RequestPeers"
    );
    jh.await.expect("join").expect("server task");
}

/// **Row:** `test_request_peers_after_connect` — `RespondPeers.peer_list` reaches [`AddressManager`].
#[tokio::test]
async fn test_request_peers_after_connect() {
    let (_cdir, _svc, h) = running_client().await;
    let server_dir = common::test_temp_dir();
    let (sc, sk) = common::generate_test_certs(server_dir.path());
    let server_cert = load_ssl_cert(&sc, &sk).expect("server tls");
    let net = common::test_network_id().to_string();
    let gossiped = TimestampedPeerInfo::new("198.51.100.42".into(), 9444, 1_700_000_000);
    let (addr, jh) =
        common::wss_full_node::spawn_one_shot_full_node(server_cert, net, vec![gossiped.clone()])
            .await;
    h.connect_to(addr).await.expect("connect");
    let (_, src) = h
        .__con001_last_address_batch_for_tests()
        .expect("batch recorded");
    assert_eq!(src.host, addr.ip().to_string());
    assert_eq!(src.port, addr.port());
    let (list, _) = h.__con001_last_address_batch_for_tests().unwrap();
    assert_eq!(list.len(), 1);
    assert_eq!(list[0].host, gossiped.host);
    assert_eq!(list[0].port, gossiped.port);
    jh.await.expect("join").expect("server");
}

/// **Row:** `test_outbound_connect_failure` — unreachable WSS peer surfaces [`GossipError::ClientError`].
#[tokio::test]
async fn test_outbound_connect_failure() {
    let (_cdir, _svc, h) = running_client().await;
    let dead: std::net::SocketAddr = "127.0.0.1:2".parse().unwrap();
    let err = h.connect_to(dead).await.unwrap_err();
    assert!(
        matches!(err, GossipError::ClientError(_)),
        "expected ClientError, got {err:?}"
    );
}
